[package]
name = "twi"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
parse = { path = "../parse" }
lex = { path = "../lex" }
thiserror = "1.0.65"
lifo = "0.1.1"
